// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/landing-pages/ContentRich.tsx": () => import("../components/mockups/landing-pages/ContentRich.tsx"),
  "./components/mockups/landing-pages/ConversionFirst.tsx": () => import("../components/mockups/landing-pages/ConversionFirst.tsx"),
  "./components/mockups/landing-pages/PremiumAuthority.tsx": () => import("../components/mockups/landing-pages/PremiumAuthority.tsx")
};
